import { SeasonStatus } from "@prisma/client";
import type { SeasonPhase } from "@/lib/world/seasons";

export interface MockSeasonRow {
  number: number;
  name: string;
  theme: string;
  researchQuestion: string;
  startsAt: string;
  submissionsClose: string;
  endsAt: string;
  status: SeasonStatus;
  phase: SeasonPhase;
  week: number;
  entries: number;
  poolAmount: number;
  sponsors: string[];
  victor: { id: string; seasonId: string; title: string; crew: { name: string; slug: string } | null } | null;
}

export const MOCK_SEASON_ROW: MockSeasonRow = {
  number: 1,
  name: "Winter I",
  theme: "Local records: what a community needs to remember, and who gets to forget",
  researchQuestion:
    "How can a community keep verifiable local records (land, identity, attendance, payments) on Avalanche infrastructure without exposing the people in them?",
  startsAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  submissionsClose: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
  endsAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
  status: SeasonStatus.ACTIVE,
  phase: "building",
  week: 2,
  entries: 4,
  poolAmount: 50000,
  sponsors: ["Avalanche Foundation", "Team1", "Isbjorn"],
  victor: null,
};

export const MOCK_SEASON_VIEW = {
  number: 1,
  name: "Winter I",
  theme: "Local records: what a community needs to remember, and who gets to forget",
  researchQuestion:
    "How can a community keep verifiable local records (land, identity, attendance, payments) on Avalanche infrastructure without exposing the people in them?",
  startsAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  submissionsClose: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
  endsAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
  retentionCheckAt: new Date(Date.now() + 118 * 24 * 60 * 60 * 1000).toISOString(),
  status: "ACTIVE",
  phase: "building",
  week: 2,
  weeks: 6,
  poolAmount: 50000,
  sponsors: ["Avalanche Foundation", "Team1", "Isbjorn"],
  panel: [
    { name: "Elena Rostova", handle: "elena", region: { name: "Madrid", slug: "madrid" } },
    { name: "Kofi Mensah", handle: "kofi", region: { name: "Nairobi", slug: "nairobi" } },
    { name: "Mateo Silva", handle: "mateo", region: { name: "Medellín", slug: "medellin" } },
  ],
  reviewerPoolSize: 18,
  rounds: [
    {
      id: "round-gtm-0",
      tournament: "GTM",
      index: 0,
      name: "Round of 16",
      threshold: 0.5,
      opensAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
      closesAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      status: "CLOSED",
      ballotCount: 142,
      totalWeight: 850,
      tally: { "gtm-1": 340, "gtm-2": 260, "gtm-3": 170, "gtm-4": 80 },
      tallyHash: "0x8f29c4ba890123efd67123aa4567890123456789abcdef0123456789abcdef01",
      advancedIds: ["gtm-1", "gtm-2", "gtm-3"],
    },
    {
      id: "round-gtm-1",
      tournament: "GTM",
      index: 1,
      name: "Quarterfinals",
      threshold: 0.5,
      opensAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      closesAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      status: "OPEN",
      ballotCount: 89,
      totalWeight: 530,
      tally: null,
      tallyHash: null,
      advancedIds: [],
    },
    {
      id: "round-gtm-2",
      tournament: "GTM",
      index: 2,
      name: "Semifinals",
      threshold: 0.5,
      opensAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      closesAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      status: "PENDING",
      ballotCount: 0,
      totalWeight: null,
      tally: null,
      tallyHash: null,
      advancedIds: [],
    },
    {
      id: "round-gtm-3",
      tournament: "GTM",
      index: 3,
      name: "Finals",
      threshold: 0.5,
      opensAt: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
      closesAt: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
      status: "PENDING",
      ballotCount: 0,
      totalWeight: null,
      tally: null,
      tallyHash: null,
      advancedIds: [],
    },
    {
      id: "round-ls-0",
      tournament: "LOCAL_SYSTEMS",
      index: 0,
      name: "Review",
      threshold: 0.6,
      opensAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      closesAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      status: "OPEN",
      ballotCount: 12,
      totalWeight: null,
      tally: null,
      tallyHash: null,
      advancedIds: [],
    },
    {
      id: "round-rp-0",
      tournament: "RESEARCH_PAPERS",
      index: 0,
      name: "Blind Review",
      threshold: 0.7,
      opensAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      closesAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      status: "OPEN",
      ballotCount: 15,
      totalWeight: null,
      tally: null,
      tallyHash: null,
      advancedIds: [],
    },
  ],
  entries: [
    {
      id: "gtm-1",
      tournament: "GTM",
      status: "ACTIVE",
      title: "GlacierPay",
      summary: "Sub-second offline-first local merchant payments settled on Avalanche C-Chain.",
      crew: { name: "Frostbite Crew", slug: "frostbite-crew", region: { name: "Medellín", slug: "medellin" } },
      faction: { name: "Polaris Faction", slug: "polaris" },
      region: { name: "Medellín", slug: "medellin" },
      author: "Mateo Silva",
      feedback: 14,
      url: "https://glacierpay.isbjorn.org",
      mine: false,
    },
    {
      id: "gtm-2",
      tournament: "GTM",
      status: "ACTIVE",
      title: "ArcticLedger",
      summary: "Verifiable community registry for land and cooperative governance records.",
      crew: { name: "Aurora Builders", slug: "aurora-builders", region: { name: "Nairobi", slug: "nairobi" } },
      faction: { name: "Borealis Alliance", slug: "borealis" },
      region: { name: "Nairobi", slug: "nairobi" },
      author: "Kofi Mensah",
      feedback: 9,
      url: "https://arcticledger.isbjorn.org",
      mine: false,
    },
    {
      id: "gtm-3",
      tournament: "GTM",
      status: "ACTIVE",
      title: "TundraID",
      summary: "Zero-knowledge proof credential issuance for municipal community hubs.",
      crew: { name: "Alpine Coders", slug: "alpine-coders", region: { name: "Madrid", slug: "madrid" } },
      region: { name: "Madrid", slug: "madrid" },
      author: "Elena Rostova",
      feedback: 18,
      url: "https://tundraid.isbjorn.org",
      mine: false,
    },
    {
      id: "gtm-4",
      tournament: "GTM",
      status: "ELIMINATED",
      eliminatedRound: 0,
      title: "Summit Relay",
      summary: "Decentralized mesh networking bridge for disaster relief telemetry.",
      crew: { name: "Kodiak Labs", slug: "kodiak-labs", region: { name: "Lima", slug: "lima" } },
      region: { name: "Lima", slug: "lima" },
      author: "Carlos Gomez",
      feedback: 5,
      mine: false,
    },
    {
      id: "ls-1",
      tournament: "LOCAL_SYSTEMS",
      status: "ACTIVE",
      title: "Water Rights Cooperative Charter",
      summary: "Constitutional governance framework and algorithmic water allocation without smart contract lock-in.",
      crew: { name: "Rio Commons", slug: "rio-commons", region: { name: "Lima", slug: "lima" } },
      author: "Sofia Morales",
      feedback: 8,
      mine: false,
    },
    {
      id: "rp-1",
      tournament: "RESEARCH_PAPERS",
      status: "ACTIVE",
      title: "Research paper (private until the season closes)",
      summary: null,
      blind: true,
      feedback: 4,
      mine: false,
    },
  ],
  alliances: [
    {
      id: "alliance-1",
      name: "Northern Front",
      factions: [
        { name: "Polaris", slug: "polaris" },
        { name: "Borealis", slug: "borealis" },
      ],
    },
  ],
  victor: null,
};

export const MOCK_ENTRIES_BY_ID: Record<string, any> = {
  "gtm-1": {
    id: "gtm-1",
    tournament: "GTM",
    status: "ACTIVE",
    title: "GlacierPay",
    summary: "Sub-second offline-first local merchant payments settled on Avalanche C-Chain.",
    body: "GlacierPay enables micro-merchants in low-connectivity areas to issue signed peer-to-peer vouchers that batch settle on Avalanche C-Chain when connectivity returns. Over 300 merchants in Medellín are piloting the system during Winter I.",
    url: "https://glacierpay.isbjorn.org",
    repoUrl: "https://github.com/frostbite/glacierpay",
    deployedOn: "Avalanche C-Chain",
    season: { number: 1, name: "Winter I", status: "ACTIVE", endsAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString() },
    crew: { name: "Frostbite Crew", slug: "frostbite-crew", region: { name: "Medellín", slug: "medellin" }, members: ["Mateo Silva", "Lucia Diaz", "Julian Perez"] },
    faction: { name: "Polaris Faction", slug: "polaris" },
    region: { name: "Medellín", slug: "medellin" },
    author: "Mateo Silva",
    meaningfulTxDefinition: "Merchant settlement voucher confirmed with Avalanche block finality.",
    metrics: [
      { label: "Piloting Merchants", value: "312", at: new Date().toISOString() },
      { label: "Daily Transactions", value: "1,840", at: new Date().toISOString() },
      { label: "Avg Settlement Latency", value: "1.2s", at: new Date().toISOString() },
    ],
    roadmap: [
      { milestone: "Offline voucher signing protocol", done: true },
      { milestone: "C-Chain batch contract deployment", done: true },
      { milestone: "Cross-region merchant pilot (Lima expansion)", done: false },
    ],
    feedback: [
      { id: "fb-1", body: "Tested the merchant terminal in Comuna 13 — offline settlement works seamlessly without internet drops.", by: "Elena R.", at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
      { id: "fb-2", body: "Clean UX on mobile. Gas sponsorship via Teleporter subnets would make this virtually free.", by: "Kofi M.", at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    retention: { day0: 312, day90: null, ratio: null, vested: null, reports: [{ activeCount: 295, walletCount: 312, reportedAt: new Date().toISOString() }] },
    mine: false,
  },
  "gtm-2": {
    id: "gtm-2",
    tournament: "GTM",
    status: "ACTIVE",
    title: "ArcticLedger",
    summary: "Verifiable community registry for land and cooperative governance records.",
    body: "ArcticLedger stores verifiable property and boundary agreements with zero-knowledge cryptographic commitments to preserve participant privacy.",
    url: "https://arcticledger.isbjorn.org",
    repoUrl: "https://github.com/aurora/arcticledger",
    deployedOn: "Avalanche C-Chain",
    season: { number: 1, name: "Winter I", status: "ACTIVE", endsAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString() },
    crew: { name: "Aurora Builders", slug: "aurora-builders", region: { name: "Nairobi", slug: "nairobi" }, members: ["Kofi Mensah", "Amina Abdi"] },
    faction: { name: "Borealis Alliance", slug: "borealis" },
    region: { name: "Nairobi", slug: "nairobi" },
    author: "Kofi Mensah",
    meaningfulTxDefinition: "Community council attested registry entry on-chain.",
    metrics: [
      { label: "Community Parcels", value: "84", at: new Date().toISOString() },
      { label: "Attested Councils", value: "6", at: new Date().toISOString() },
    ],
    roadmap: [
      { milestone: "Land registry zk-schema", done: true },
      { milestone: "Mobile validator node integration", done: true },
    ],
    feedback: [
      { id: "fb-3", body: "Crucial design for dispute resolution without centralized state dependencies.", by: "Mateo S.", at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    retention: { day0: 84, day90: null, ratio: null, vested: null, reports: [{ activeCount: 80, walletCount: 84, reportedAt: new Date().toISOString() }] },
    mine: false,
  },
  "gtm-3": {
    id: "gtm-3",
    tournament: "GTM",
    status: "ACTIVE",
    title: "TundraID",
    summary: "Zero-knowledge proof credential issuance for municipal community hubs.",
    body: "TundraID allows citizens to prove municipal membership and voting eligibility without disclosing their real identity or home address.",
    url: "https://tundraid.isbjorn.org",
    repoUrl: "https://github.com/alpine/tundraid",
    deployedOn: "Avalanche C-Chain",
    season: { number: 1, name: "Winter I", status: "ACTIVE", endsAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString() },
    crew: { name: "Alpine Coders", slug: "alpine-coders", region: { name: "Madrid", slug: "madrid" }, members: ["Elena Rostova", "Pablo Ruiz"] },
    faction: null,
    region: { name: "Madrid", slug: "madrid" },
    author: "Elena Rostova",
    meaningfulTxDefinition: "Zero-knowledge credential proof verified against smart contract.",
    metrics: [
      { label: "Verified Citizens", value: "540", at: new Date().toISOString() },
      { label: "Proof Verifications", value: "2,190", at: new Date().toISOString() },
    ],
    roadmap: [
      { milestone: "Groth16 verifier contract on Avalanche", done: true },
      { milestone: "Mobile identity enclave storage", done: true },
    ],
    feedback: [
      { id: "fb-4", body: "Very impressive circuit generation times on mobile devices.", by: "Kofi M.", at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    retention: { day0: 540, day90: null, ratio: null, vested: null, reports: [{ activeCount: 512, walletCount: 540, reportedAt: new Date().toISOString() }] },
    mine: false,
  },
  "gtm-4": {
    id: "gtm-4",
    tournament: "GTM",
    status: "ELIMINATED",
    title: "Summit Relay",
    summary: "Decentralized mesh networking bridge for disaster relief telemetry.",
    body: "Long-range LoRaWAN telemetry bridged to Avalanche subnets during emergency response situations.",
    season: { number: 1, name: "Winter I", status: "ACTIVE", endsAt: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString() },
    crew: { name: "Kodiak Labs", slug: "kodiak-labs", region: { name: "Lima", slug: "lima" }, members: ["Carlos Gomez"] },
    faction: null,
    region: { name: "Lima", slug: "lima" },
    author: "Carlos Gomez",
    metrics: [{ label: "Mesh Relays", value: "14", at: new Date().toISOString() }],
    feedback: [],
    retention: { day0: 14, day90: null, ratio: null, vested: null, reports: [] },
    mine: false,
  },
};

export const MOCK_ROUNDS_BY_ID: Record<string, any> = {
  "round-gtm-1": {
    id: "round-gtm-1",
    season: { number: 1, name: "Winter I" },
    tournament: "GTM",
    index: 1,
    name: "Quarterfinals",
    threshold: 0.5,
    opensAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    closesAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: "OPEN",
    ballotCount: 89,
    totalWeight: 530,
    tallyHash: null,
    entries: [
      { id: "gtm-1", title: "GlacierPay", summary: "Sub-second offline-first local merchant payments settled on Avalanche C-Chain.", url: "https://glacierpay.isbjorn.org", crew: { name: "Frostbite Crew", slug: "frostbite-crew" }, faction: { name: "Polaris Faction", slug: "polaris" }, status: "ACTIVE", weight: null, share: null, advanced: false },
      { id: "gtm-2", title: "ArcticLedger", summary: "Verifiable community registry for land and cooperative governance records.", url: "https://arcticledger.isbjorn.org", crew: { name: "Aurora Builders", slug: "aurora-builders" }, faction: { name: "Borealis Alliance", slug: "borealis" }, status: "ACTIVE", weight: null, share: null, advanced: false },
      { id: "gtm-3", title: "TundraID", summary: "Zero-knowledge proof credential issuance for municipal community hubs.", url: "https://tundraid.isbjorn.org", crew: { name: "Alpine Coders", slug: "alpine-coders" }, faction: null, status: "ACTIVE", weight: null, share: null, advanced: false },
    ],
    viewer: { canVote: true, weight: 1.0, voted: false, reason: null },
  },
  "round-gtm-0": {
    id: "round-gtm-0",
    season: { number: 1, name: "Winter I" },
    tournament: "GTM",
    index: 0,
    name: "Round of 16",
    threshold: 0.5,
    opensAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    closesAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    status: "CLOSED",
    ballotCount: 142,
    totalWeight: 850,
    tallyHash: "0x8f29c4ba890123efd67123aa4567890123456789abcdef0123456789abcdef01",
    entries: [
      { id: "gtm-1", title: "GlacierPay", summary: "Sub-second offline-first local merchant payments settled on Avalanche C-Chain.", url: "https://glacierpay.isbjorn.org", crew: { name: "Frostbite Crew", slug: "frostbite-crew" }, faction: { name: "Polaris Faction", slug: "polaris" }, status: "ACTIVE", weight: 340, share: 0.4, advanced: true },
      { id: "gtm-2", title: "ArcticLedger", summary: "Verifiable community registry for land and cooperative governance records.", url: "https://arcticledger.isbjorn.org", crew: { name: "Aurora Builders", slug: "aurora-builders" }, faction: { name: "Borealis Alliance", slug: "borealis" }, status: "ACTIVE", weight: 260, share: 0.31, advanced: true },
      { id: "gtm-3", title: "TundraID", summary: "Zero-knowledge proof credential issuance for municipal community hubs.", url: "https://tundraid.isbjorn.org", crew: { name: "Alpine Coders", slug: "alpine-coders" }, faction: null, status: "ACTIVE", weight: 170, share: 0.2, advanced: true },
      { id: "gtm-4", title: "Summit Relay", summary: "Decentralized mesh networking bridge for disaster relief telemetry.", url: null, crew: { name: "Kodiak Labs", slug: "kodiak-labs" }, faction: null, status: "ELIMINATED", weight: 80, share: 0.09, advanced: false },
    ],
    viewer: { canVote: false, weight: 0, voted: false, reason: "Round closed" },
  },
};
